import React, {useMemo, useState} from "react";
import {
  LayoutDashboard, CarFront, Users, UserRoundSearch, BadgeDollarSign, CalendarDays,
  FileText, BarChart3, Settings, Search, Menu, Plus, Eye, Pencil, MoreVertical,
  Trash2, CheckCircle2, AlertCircle, Clock3, X, ChevronRight, TrendingUp, Wallet,
  CircleDollarSign, LogOut, Download, Upload, ExternalLink, Filter, RefreshCw
} from "lucide-react";
import {loadDB, saveDB, resetDemo, emptyDB, nextId} from "./storage";

const money = n => new Intl.NumberFormat("es-CR",{style:"currency",currency:"CRC",maximumFractionDigits:0}).format(Number(n)||0);
const dateFmt = d => d ? new Intl.DateTimeFormat("es-CR",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(d+"T12:00:00")) : "—";
const today = () => new Date().toISOString().slice(0,10);
const daysSince = d => Math.max(0, Math.floor((new Date(today()+"T12:00:00")-new Date(d+"T12:00:00"))/86400000));
const statusClass = s => "status " + String(s).toLowerCase().replaceAll(" ","-");
const statuses = ["Prospecto","Pendiente","Publicado","Interesado","Negociación","Vendido","Retirado"];

function Modal({title,onClose,children,wide=false}) {
  return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}>
    <div className={"modal "+(wide?"wide":"")}><div className="modal-head"><h3>{title}</h3><button className="icon-btn" onClick={onClose}><X size={18}/></button></div>{children}</div>
  </div>
}
function Field({label,children}){return <label className="field"><span>{label}</span>{children}</label>}
function Empty({title,text,action}){return <div className="empty"><div className="empty-icon"><CarFront size={24}/></div><h3>{title}</h3><p>{text}</p>{action}</div>}

export default function App(){
  const [db,setDb] = useState(loadDB);
  const [page,setPage] = useState("dashboard");
  const [selected,setSelected] = useState(null);
  const [query,setQuery] = useState("");
  const [mobileOpen,setMobileOpen] = useState(false);
  const [logged,setLogged] = useState(()=>sessionStorage.getItem("has_logged")==="1");
  const [modal,setModal] = useState(null);

  const update = fn => setDb(prev=>{const n=fn(structuredClone(prev));saveDB(n);return n});
  const active = db.vehicles.filter(v=>!["Vendido","Retirado"].includes(v.status));
  const month = new Date().toISOString().slice(0,7);
  const salesMonth = db.sales.filter(s=>s.date?.startsWith(month));
  const commissions = db.sales.reduce((a,s)=>a+(Number(s.commission)||0),0);
  const pending = db.sales.filter(s=>s.commissionStatus==="Pendiente").reduce((a,s)=>a+(Number(s.commission)||0),0);

  if(!logged) return <Login onLogin={()=>{sessionStorage.setItem("has_logged","1");setLogged(true)}}/>;

  const nav = [
    ["dashboard","Panel Principal",LayoutDashboard],["vehicles","Vehículos",CarFront],["owners","Propietarios",Users],
    ["leads","Interesados",UserRoundSearch],["sales","Ventas",BadgeDollarSign],["followups","Calendario / Seguimientos",CalendarDays],
    ["documents","Documentos",FileText],["reports","Reportes",BarChart3],["settings","Configuración",Settings]
  ];

  function go(p){setPage(p);setSelected(null);setMobileOpen(false)}
  return <div className="app">
    <aside className={"sidebar "+(mobileOpen?"open":"")}>
      <div className="brand"><div className="brand-mark">HA</div><div><strong>HERRERA</strong><span>AUTO SALES</span></div></div>
      <div className="brand-sub">COMPRA • VENTA • INTERMEDIACIÓN</div>
      <nav>{nav.map(([id,label,Icon])=><button key={id} className={page===id?"nav active":"nav"} onClick={()=>go(id)}><Icon size={18}/><span>{label}</span></button>)}</nav>
      <div className="sidebar-bottom"><div className="user-mini"><div className="avatar">VH</div><div><b>Victor Herrera</b><small>Administrador</small></div></div><button className="nav" onClick={()=>{sessionStorage.removeItem("has_logged");setLogged(false)}}><LogOut size={17}/>Cerrar sesión</button></div>
    </aside>
    <main className="main">
      <header className="topbar"><button className="menu-btn" onClick={()=>setMobileOpen(!mobileOpen)}><Menu/></button><div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar ID, placa, VIN, propietario, interesado..."/></div><div className="top-actions"><span className="live-dot"></span><span>Datos guardados localmente</span></div></header>
      <div className="content">
        {page==="dashboard" && <Dashboard active={active} salesMonth={salesMonth} commissions={commissions} pending={pending} db={db} money={money} dateFmt={dateFmt} go={go}/>}
        {page==="vehicles" && <Vehicles db={db} update={update} query={query} setModal={setModal} selected={selected} setSelected={setSelected} go={go}/>}
        {page==="owners" && <Owners db={db} update={update} query={query} setModal={setModal}/>}
        {page==="leads" && <Leads db={db} update={update} query={query} setModal={setModal}/>}
        {page==="followups" && <Followups db={db} update={update} setModal={setModal}/>}
        {page==="sales" && <Sales db={db} update={update}/>}
        {page==="documents" && <Documents db={db} update={update}/>}
        {page==="reports" && <Reports db={db}/>}
        {page==="settings" && <SettingsPage db={db} setDb={setDb}/>}
      </div>
    </main>
    {modal==="vehicle" && <VehicleModal db={db} update={update} onClose={()=>setModal(null)}/>}
    {modal?.type==="vehicle" && <VehicleModal db={db} update={update} edit={modal.vehicle} onClose={()=>setModal(null)}/>}
    {modal==="owner" && <OwnerModal db={db} update={update} onClose={()=>setModal(null)}/>}
    {modal?.type==="owner" && <OwnerModal db={db} update={update} edit={modal.owner} onClose={()=>setModal(null)}/>}
    {modal==="lead" && <LeadModal db={db} update={update} onClose={()=>setModal(null)}/>}
    {modal==="followup" && <FollowupModal db={db} update={update} onClose={()=>setModal(null)}/>}
  </div>
}

function Login({onLogin}){
  const [user,setUser]=useState(""); const [pass,setPass]=useState(""); const [err,setErr]=useState("");
  return <div className="login"><div className="login-card"><div className="brand centered"><div className="brand-mark">HA</div><div><strong>HERRERA</strong><span>AUTO SALES</span></div></div><div className="login-kicker">SISTEMA DE GESTIÓN</div><h1>Bienvenido de nuevo</h1><p>Administra tu cartera de vehículos desde un solo lugar.</p><form onSubmit={e=>{e.preventDefault();if((user==="Victor Herrera Andres Valle"||user==="victor")&&pass==="admin"){onLogin()}else setErr("Usuario o contraseña incorrectos.")}}><Field label="Correo / usuario"><input value={user} onChange={e=>setUser(e.target.value)} placeholder="Usuario"/></Field><Field label="Contraseña"><input type="password" value={pass} onChange={e=>setPass(e.target.value)} placeholder="••••••••"/></Field>{err&&<div className="error"><AlertCircle size={16}/>{err}</div>}<button className="btn primary full">INICIAR SESIÓN</button></form><small className="hint">Demo local: usuario <b>victor</b> · contraseña <b>admin</b></small></div></div>
}

function Dashboard({active,salesMonth,commissions,pending,db,money,dateFmt,go}){
  const inventory=active.reduce((a,v)=>a+Number(v.price||0),0);
  const upcoming=db.followups.filter(f=>f.date>=today()&&f.status!=="Completado").sort((a,b)=>a.date.localeCompare(b.date)).slice(0,5);
  return <><div className="page-head"><div><div className="eyebrow">PANEL PRINCIPAL</div><h1>Bienvenido, Victor</h1><p>Aquí tienes un resumen de tu negocio.</p></div><button className="btn primary" onClick={()=>go("vehicles")}><Plus size={17}/> REGISTRAR VEHÍCULO</button></div>
    <div className="kpis">
      <Kpi icon={CarFront} label="Vehículos activos" value={active.length} meta="En cartera actual"/>
      <Kpi icon={Wallet} label="Valor total en inventario" value={money(inventory)} meta="Precio de publicación"/>
      <Kpi icon={CircleDollarSign} label="Ventas del mes" value={salesMonth.length} meta="Operaciones cerradas"/>
      <Kpi icon={TrendingUp} label="Comisiones generadas" value={money(commissions)} meta="Acumulado registrado"/>
      <Kpi icon={Clock3} label="Comisiones pendientes" value={money(pending)} meta="Por cobrar" alert={pending>0}/>
    </div>
    <div className="grid-2"><section className="panel"><div className="panel-head"><div><h2>Próximos seguimientos</h2><p>Agenda de tareas pendientes</p></div><button className="text-btn" onClick={()=>go("followups")}>Ver calendario <ChevronRight size={15}/></button></div>{upcoming.length?upcoming.map(f=><div className="follow-row" key={f.id}><div className="date-tile"><b>{new Date(f.date+"T12:00:00").getDate()}</b><span>{new Intl.DateTimeFormat("es-CR",{month:"short"}).format(new Date(f.date+"T12:00:00")).toUpperCase()}</span></div><div><b>{db.vehicles.find(v=>v.id===f.vehicleId)?.brand} {db.vehicles.find(v=>v.id===f.vehicleId)?.model}</b><span>{f.description}</span></div><span className={f.date<today()?"late":"soft"}>{f.time}</span></div>):<Empty title="Sin seguimientos" text="No hay tareas próximas."/>}</section>
    <section className="panel"><div className="panel-head"><div><h2>Inventario reciente</h2><p>Últimos vehículos registrados</p></div><button className="text-btn" onClick={()=>go("vehicles")}>Ver vehículos <ChevronRight size={15}/></button></div>{active.slice(0,5).map(v=><div className="inventory-row" key={v.id}><div className="car-thumb"><CarFront size={18}/></div><div className="grow"><b>{v.brand} {v.model} {v.year}</b><span>{v.id} · {v.owner}</span></div><div className="right"><b>{money(v.price)}</b><span className={statusClass(v.status)}>{v.status}</span></div></div>)}</section></div>
  </>
}
function Kpi({icon:Icon,label,value,meta,alert}){return <div className={"kpi "+(alert?"kpi-alert":"")}><div className="kpi-icon"><Icon size={19}/></div><div><span>{label}</span><strong>{value}</strong><small>{meta}</small></div></div>}

function Vehicles({db,update,query,setModal,setSelected,selected,go}){
  const [status,setStatus]=useState("Todos"),[brand,setBrand]=useState("Todas"),[sort,setSort]=useState("Fecha de ingreso");
  const filtered=useMemo(()=>db.vehicles.filter(v=>{
    const q=query.toLowerCase(); const match=!q||[v.id,v.brand,v.model,v.plate,v.vin,v.owner,v.ownerPhone].join(" ").toLowerCase().includes(q);
    return match&&(status==="Todos"||v.status===status)&&(brand==="Todas"||v.brand===brand);
  }).sort((a,b)=>sort==="Precio"?b.price-a.price:sort==="Comisión"?((b.price*b.commissionPct)-(a.price*a.commissionPct)):sort==="Año"?b.year-a.year:sort==="Días publicado"?daysSince(b.entryDate)-daysSince(a.entryDate):b.entryDate.localeCompare(a.entryDate)),[db.vehicles,query,status,brand,sort]);
  const del=id=>{if(confirm("¿Eliminar este vehículo? Esta acción no se puede deshacer."))update(d=>({...d,vehicles:d.vehicles.filter(v=>v.id!==id)}))};
  if(selected){const v=db.vehicles.find(x=>x.id===selected); if(!v){setSelected(null);return null} return <VehicleDetail v={v} db={db} update={update} onBack={()=>setSelected(null)} setModal={setModal}/>}
  const brands=[...new Set(db.vehicles.map(v=>v.brand))];
  return <><div className="page-head"><div><div className="eyebrow">CARTERA</div><h1>Vehículos</h1><p>Administra tu inventario, ofertas y oportunidades.</p></div><button className="btn primary" onClick={()=>setModal("vehicle")}><Plus size={17}/> REGISTRAR VEHÍCULO</button></div>
    <div className="filters"><div className="filter-search"><Search size={16}/><span>{filtered.length} resultados</span></div><select value={status} onChange={e=>setStatus(e.target.value)}><option>Todos</option>{statuses.map(s=><option key={s}>{s}</option>)}</select><select value={brand} onChange={e=>setBrand(e.target.value)}><option>Todas</option>{brands.map(b=><option key={b}>{b}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value)}><option>Fecha de ingreso</option><option>Precio</option><option>Comisión</option><option>Año</option><option>Días publicado</option></select></div>
    <section className="panel table-panel"><div className="table-scroll"><table><thead><tr><th>ID</th><th>Vehículo</th><th>Propietario</th><th>Precio</th><th>Precio mínimo</th><th>Comisión</th><th>Estado</th><th>Ingreso</th><th>Días</th><th>Interesados</th><th>Última oferta</th><th>Próximo seguimiento</th><th></th></tr></thead><tbody>{filtered.map(v=><tr key={v.id}><td><b className="gold">{v.id}</b></td><td><b>{v.brand} {v.model} {v.year}</b><small>{v.version}</small></td><td>{v.owner}<small>{v.ownerPhone}</small></td><td><b>{money(v.price)}</b></td><td>{money(v.minPrice)}</td><td>{money(v.price*v.commissionPct/100)}<small>{v.commissionPct}%</small></td><td><span className={statusClass(v.status)}>{v.status}</span></td><td>{dateFmt(v.entryDate)}</td><td>{daysSince(v.entryDate)}</td><td>{v.interestedCount||0}</td><td>{v.lastOffer?money(v.lastOffer):"—"}</td><td>{dateFmt(v.nextFollowup)}</td><td><div className="row-actions"><button className="icon-btn" title="Ver" onClick={()=>setSelected(v.id)}><Eye size={16}/></button><button className="icon-btn" title="Editar" onClick={()=>setModal({type:"vehicle",vehicle:v})}><Pencil size={16}/></button><button className="icon-btn danger" title="Eliminar" onClick={()=>del(v.id)}><Trash2 size={16}/></button></div></td></tr>)}</tbody></table></div>{!filtered.length&&<Empty title="No hay vehículos que coincidan" text="Prueba otros filtros o registra un nuevo vehículo."/>}</section></>
}

function VehicleDetail({v,db,update,onBack,setModal}){
 const [newStatus,setNewStatus]=useState(v.status);
 const saveStatus=()=>update(d=>({...d,vehicles:d.vehicles.map(x=>x.id===v.id?{...x,status:newStatus,activity:[...(x.activity||[]),{date:today(),text:`Estado cambiado a ${newStatus}.` }]}:x)}));
 const owner=db.owners.find(o=>o.name===v.owner);
 return <><div className="back" onClick={onBack}>← Volver a vehículos</div><div className="detail-head"><div><div className="eyebrow">{v.id}</div><h1>{v.brand} {v.model} {v.year}</h1><p>{v.version} · {v.color} · {v.transmission}</p></div><div className="detail-actions"><button className="btn" onClick={()=>setModal({type:"vehicle",vehicle:v})}><Pencil size={16}/> Editar</button><select value={newStatus} onChange={e=>setNewStatus(e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select><button className="btn primary" onClick={saveStatus}>Guardar estado</button></div></div>
 <div className="detail-grid"><section className="panel hero-car"><div className="gallery"><div className="gallery-empty"><CarFront size={42}/><span>Galería del vehículo</span></div></div><div className="price-row"><div><span>Precio de publicación</span><strong>{money(v.price)}</strong></div><div><span>Comisión estimada</span><strong>{money(v.price*v.commissionPct/100)}</strong></div><span className={statusClass(v.status)}>{v.status}</span></div></section>
 <section className="panel"><div className="panel-head"><div><h2>Información del vehículo</h2><p>Datos técnicos y comerciales</p></div></div><div className="info-grid">{[["Marca",v.brand],["Modelo",v.model],["Año",v.year],["Versión",v.version],["Kilometraje",(v.mileage||0).toLocaleString()+" km"],["Transmisión",v.transmission],["Combustible",v.fuel],["Color",v.color],["Placa",v.plate],["VIN / Chasis",v.vin],["Precio mínimo",money(v.minPrice)],["Comisión",v.commissionPct+"%"],["Ingreso",dateFmt(v.entryDate)],["Publicación",dateFmt(v.publishDate)]].map(([a,b])=><div key={a}><span>{a}</span><b>{b||"—"}</b></div>)}</div></section>
 <section className="panel"><div className="panel-head"><div><h2>Propietario</h2></div></div>{owner?<div className="owner-card"><div className="avatar large">{owner.name.split(" ").map(x=>x[0]).slice(0,2).join("")}</div><div><b>{owner.name}</b><span>{owner.phone} · {owner.email||"Sin correo"}</span><span>{owner.address||"Sin dirección"}</span></div></div>:<p>Propietario registrado como {v.owner} · {v.ownerPhone}</p>}</section>
 <section className="panel"><div className="panel-head"><div><h2>Actividad</h2><p>Historial cronológico</p></div></div><div className="timeline">{(v.activity||[]).slice().reverse().map((a,i)=><div className="timeline-item" key={i}><div className="timeline-dot"></div><div><b>{a.text}</b><span>{dateFmt(a.date)}</span></div></div>)}</div></section>
 <section className="panel"><div className="panel-head"><div><h2>Ofertas</h2><p>Historial de negociación</p></div></div>{(v.offers||[]).length?(v.offers.map((o,i)=><div className="offer-row" key={i}><span>{dateFmt(o.date)}</span><b>{o.name}</b><strong>{money(o.amount)}</strong></div>)): <p className="muted">No hay ofertas registradas.</p>}</section>
 <section className="panel"><div className="panel-head"><div><h2>Interesados</h2><p>{v.interestedCount||0} registrados</p></div></div><div className="big-number">{v.interestedCount||0}</div></section>
 </div></>
}

function VehicleModal({db,update,onClose,edit}){
 const base=edit||{brand:"",model:"",year:new Date().getFullYear(),version:"",mileage:"",transmission:"Automática",fuel:"Gasolina",color:"",plate:"",vin:"",price:"",minPrice:"",commissionPct:3,owner:"",ownerPhone:"",entryDate:today(),publishDate:"",status:"Prospecto",lastOffer:"",interestedCount:0,nextFollowup:"",notes:"",links:[],photos:[],offers:[],activity:[]};
 const [f,setF]=useState(base); const set=(k,v)=>setF(x=>({...x,[k]:v})); const comm=(Number(f.price)||0)*(Number(f.commissionPct)||0)/100;
 const submit=e=>{e.preventDefault(); update(d=>{const v={...f,price:Number(f.price)||0,minPrice:Number(f.minPrice)||0,mileage:Number(f.mileage)||0,commissionPct:Number(f.commissionPct)||0,lastOffer:Number(f.lastOffer)||0,interestedCount:Number(f.interestedCount)||0};if(edit)return {...d,vehicles:d.vehicles.map(x=>x.id===edit.id?{...x,...v}:x)};return {...d,vehicles:[...d.vehicles,{...v,id:nextId(d.vehicles,"HAS"),activity:[{date:today(),text:"Vehículo registrado."}],offers:[]}]}});onClose()};
 return <Modal title={edit?`Editar ${edit.id}`:"Registrar vehículo"} onClose={onClose} wide><form onSubmit={submit}><div className="form-section"><h4>Información básica</h4><div className="form-grid"><Field label="Marca"><input required value={f.brand} onChange={e=>set("brand",e.target.value)}/></Field><Field label="Modelo"><input required value={f.model} onChange={e=>set("model",e.target.value)}/></Field><Field label="Año"><input type="number" value={f.year} onChange={e=>set("year",e.target.value)}/></Field><Field label="Versión"><input value={f.version} onChange={e=>set("version",e.target.value)}/></Field></div></div>
 <div className="form-section"><h4>Información técnica</h4><div className="form-grid"><Field label="Kilometraje"><input type="number" value={f.mileage} onChange={e=>set("mileage",e.target.value)}/></Field><Field label="Transmisión"><select value={f.transmission} onChange={e=>set("transmission",e.target.value)}><option>Automática</option><option>Manual</option><option>CVT</option></select></Field><Field label="Combustible"><select value={f.fuel} onChange={e=>set("fuel",e.target.value)}><option>Gasolina</option><option>Diésel</option><option>Híbrido</option><option>Eléctrico</option></select></Field><Field label="Color"><input value={f.color} onChange={e=>set("color",e.target.value)}/></Field><Field label="Placa"><input value={f.plate} onChange={e=>set("plate",e.target.value)}/></Field><Field label="VIN / Chasis"><input value={f.vin} onChange={e=>set("vin",e.target.value)}/></Field></div></div>
 <div className="form-section"><h4>Información comercial</h4><div className="form-grid"><Field label="Precio de publicación"><input type="number" required value={f.price} onChange={e=>set("price",e.target.value)}/></Field><Field label="Precio mínimo autorizado"><input type="number" value={f.minPrice} onChange={e=>set("minPrice",e.target.value)}/></Field><Field label="Comisión %"><input type="number" step="0.1" value={f.commissionPct} onChange={e=>set("commissionPct",e.target.value)}/></Field><div className="calc-box"><span>Comisión estimada</span><strong>{money(comm)}</strong></div></div></div>
 <div className="form-section"><h4>Propietario</h4><div className="form-grid"><Field label="Propietario"><select value={f.owner} onChange={e=>{set("owner",e.target.value);set("ownerPhone",db.owners.find(o=>o.name===e.target.value)?.phone||"")}}><option value="">Seleccionar...</option>{db.owners.map(o=><option key={o.id}>{o.name}</option>)}</select></Field><Field label="Teléfono"><input value={f.ownerPhone} onChange={e=>set("ownerPhone",e.target.value)}/></Field></div><small className="muted">También puedes crear propietarios desde el módulo Propietarios.</small></div>
 <div className="form-section"><h4>Publicación y seguimiento</h4><div className="form-grid"><Field label="Estado"><select value={f.status} onChange={e=>set("status",e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></Field><Field label="Fecha de ingreso"><input type="date" value={f.entryDate} onChange={e=>set("entryDate",e.target.value)}/></Field><Field label="Fecha de publicación"><input type="date" value={f.publishDate} onChange={e=>set("publishDate",e.target.value)}/></Field><Field label="Próximo seguimiento"><input type="date" value={f.nextFollowup} onChange={e=>set("nextFollowup",e.target.value)}/></Field><Field label="Última oferta"><input type="number" value={f.lastOffer} onChange={e=>set("lastOffer",e.target.value)}/></Field><Field label="Interesados"><input type="number" value={f.interestedCount} onChange={e=>set("interestedCount",e.target.value)}/></Field></div><Field label="Enlaces de publicaciones"><input value={(f.links||[]).join(", ")} onChange={e=>set("links",e.target.value.split(",").map(x=>x.trim()).filter(Boolean))} placeholder="Facebook, Instagram, TikTok..." /></Field><Field label="Observaciones"><textarea value={f.notes} onChange={e=>set("notes",e.target.value)} rows="3"/></Field></div>
 <div className="modal-foot"><button type="button" className="btn" onClick={onClose}>Cancelar</button><button className="btn primary">{edit?"Guardar cambios":"Registrar vehículo"}</button></div></form></Modal>
}

function Owners({db,update,query,setModal}){
 const list=db.owners.filter(o=>[o.name,o.cedula,o.phone,o.email].join(" ").toLowerCase().includes(query.toLowerCase()));
 const del=id=>{if(confirm("¿Eliminar propietario?"))update(d=>({...d,owners:d.owners.filter(o=>o.id!==id)}))};
 return <><div className="page-head"><div><div className="eyebrow">RELACIONES</div><h1>Propietarios</h1><p>Personas que confían sus vehículos a Herrera Auto Sales.</p></div><button className="btn primary" onClick={()=>setModal("owner")}><Plus size={17}/> NUEVO PROPIETARIO</button></div><section className="panel table-panel"><div className="table-scroll"><table><thead><tr><th>Propietario</th><th>Cédula</th><th>Teléfono</th><th>Correo</th><th>Vehículos</th><th>Operaciones</th><th></th></tr></thead><tbody>{list.map(o=>{const vs=db.vehicles.filter(v=>v.owner===o.name);return <tr key={o.id}><td><div className="person"><div className="avatar">{o.name.split(" ").map(x=>x[0]).slice(0,2).join("")}</div><b>{o.name}</b></div></td><td>{o.cedula}</td><td>{o.phone}</td><td>{o.email||"—"}</td><td>{vs.length}</td><td>{vs.filter(v=>v.status==="Vendido").length} vendidos</td><td><div className="row-actions"><button className="icon-btn" onClick={()=>setModal({type:"owner",owner:o})}><Pencil size={16}/></button><button className="icon-btn danger" onClick={()=>del(o.id)}><Trash2 size={16}/></button></div></td></tr>})}</tbody></table></div>{!list.length&&<Empty title="No hay propietarios" text="Registra el primer propietario de tu cartera."/>}</section></>
}
function OwnerModal({db,update,onClose,edit}){
 const [f,setF]=useState(edit||{name:"",cedula:"",phone:"",whatsapp:"",email:"",address:"",notes:""});const set=(k,v)=>setF(x=>({...x,[k]:v}));
 const submit=e=>{e.preventDefault();update(d=>edit?({...d,owners:d.owners.map(x=>x.id===edit.id?{...x,...f}:x)}):({...d,owners:[...d.owners,{...f,id:nextId(d.owners,"OWN")}] }));onClose()};
 return <Modal title={edit?"Editar propietario":"Nuevo propietario"} onClose={onClose}><form onSubmit={submit}><div className="form-grid"><Field label="Nombre completo"><input required value={f.name} onChange={e=>set("name",e.target.value)}/></Field><Field label="Cédula"><input value={f.cedula} onChange={e=>set("cedula",e.target.value)}/></Field><Field label="Teléfono"><input value={f.phone} onChange={e=>set("phone",e.target.value)}/></Field><Field label="WhatsApp"><input value={f.whatsapp} onChange={e=>set("whatsapp",e.target.value)}/></Field><Field label="Correo"><input type="email" value={f.email} onChange={e=>set("email",e.target.value)}/></Field><Field label="Dirección"><input value={f.address} onChange={e=>set("address",e.target.value)}/></Field></div><Field label="Notas"><textarea rows="4" value={f.notes} onChange={e=>set("notes",e.target.value)}/></Field><div className="modal-foot"><button type="button" className="btn" onClick={onClose}>Cancelar</button><button className="btn primary">Guardar</button></div></form></Modal>
}
function Leads({db,update,query,setModal}){
 const [filter,setFilter]=useState("Todos"); const list=db.leads.filter(l=>[l.name,l.phone,l.email].join(" ").toLowerCase().includes(query.toLowerCase())&&(filter==="Todos"||l.status===filter));
 const states=["Nuevo","Contactado","Visita pendiente","Visitó vehículo","Oferta realizada","Negociación","Compró","No interesado"];
 return <><div className="page-head"><div><div className="eyebrow">CRM</div><h1>Interesados</h1><p>Gestiona compradores, ofertas y oportunidades.</p></div><button className="btn primary" onClick={()=>setModal("lead")}><Plus size={17}/> NUEVO INTERESADO</button></div><div className="chips">{["Todos",...states].map(s=><button className={filter===s?"chip active":"chip"} onClick={()=>setFilter(s)} key={s}>{s}</button>)}</div><section className="panel table-panel"><div className="table-scroll"><table><thead><tr><th>Interesado</th><th>Vehículo</th><th>Contacto</th><th>Oferta</th><th>Estado</th><th>Próximo seguimiento</th><th></th></tr></thead><tbody>{list.map(l=>{const v=db.vehicles.find(v=>v.id===l.vehicleId);return <tr key={l.id}><td><b>{l.name}</b><small>{l.email||"Sin correo"}</small></td><td>{v?`${v.brand} ${v.model} ${v.year}`:"—"}</td><td>{l.phone}</td><td>{l.offer?money(l.offer):"—"}</td><td><span className="status status-interesado">{l.status}</span></td><td>{dateFmt(l.nextFollowup)}</td><td><button className="icon-btn danger" onClick={()=>{if(confirm("¿Eliminar interesado?"))update(d=>({...d,leads:d.leads.filter(x=>x.id!==l.id)}))}}><Trash2 size={16}/></button></td></tr>})}</tbody></table></div>{!list.length&&<Empty title="No hay interesados" text="Registra personas interesadas en tus vehículos."/>}</section></>
}
function LeadModal({db,update,onClose}){
 const [f,setF]=useState({name:"",phone:"",whatsapp:"",email:"",vehicleId:"",contactDate:today(),offer:"",status:"Nuevo",nextFollowup:"",notes:""});const set=(k,v)=>setF(x=>({...x,[k]:v}));
 const submit=e=>{e.preventDefault();update(d=>({...d,leads:[...d.leads,{...f,id:nextId(d.leads,"LEAD"),offer:Number(f.offer)||0}],vehicles:d.vehicles.map(v=>v.id===f.vehicleId?{...v,interestedCount:(v.interestedCount||0)+1}:v)}));onClose()};
 return <Modal title="Nuevo interesado" onClose={onClose}><form onSubmit={submit}><div className="form-grid"><Field label="Nombre"><input required value={f.name} onChange={e=>set("name",e.target.value)}/></Field><Field label="Teléfono"><input required value={f.phone} onChange={e=>set("phone",e.target.value)}/></Field><Field label="WhatsApp"><input value={f.whatsapp} onChange={e=>set("whatsapp",e.target.value)}/></Field><Field label="Correo"><input value={f.email} onChange={e=>set("email",e.target.value)}/></Field><Field label="Vehículo de interés"><select value={f.vehicleId} onChange={e=>set("vehicleId",e.target.value)}><option value="">Seleccionar...</option>{db.vehicles.filter(v=>v.status!=="Vendido").map(v=><option key={v.id} value={v.id}>{v.id} · {v.brand} {v.model}</option>)}</select></Field><Field label="Fecha de contacto"><input type="date" value={f.contactDate} onChange={e=>set("contactDate",e.target.value)}/></Field><Field label="Oferta realizada"><input type="number" value={f.offer} onChange={e=>set("offer",e.target.value)}/></Field><Field label="Estado"><select value={f.status} onChange={e=>set("status",e.target.value)}>{["Nuevo","Contactado","Visita pendiente","Visitó vehículo","Oferta realizada","Negociación","Compró","No interesado"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Próximo seguimiento"><input type="date" value={f.nextFollowup} onChange={e=>set("nextFollowup",e.target.value)}/></Field></div><Field label="Notas"><textarea rows="4" value={f.notes} onChange={e=>set("notes",e.target.value)}/></Field><div className="modal-foot"><button type="button" className="btn" onClick={onClose}>Cancelar</button><button className="btn primary">Guardar interesado</button></div></form></Modal>
}
function Followups({db,update,setModal}){
 const sorted=[...db.followups].sort((a,b)=>a.date.localeCompare(b.date)||a.time.localeCompare(b.time)); const complete=id=>update(d=>({...d,followups:d.followups.map(f=>f.id===id?{...f,status:"Completado"}:f)}));
 const groups=[["Atrasados",sorted.filter(f=>f.date<today()&&f.status!=="Completado")],["Hoy",sorted.filter(f=>f.date===today()&&f.status!=="Completado")],["Próximos",sorted.filter(f=>f.date>today()&&f.status!=="Completado")],["Completados",sorted.filter(f=>f.status==="Completado")]];
 return <><div className="page-head"><div><div className="eyebrow">AGENDA</div><h1>Calendario / Seguimientos</h1><p>Controla tus próximos contactos y tareas.</p></div><button className="btn primary" onClick={()=>setModal("followup")}><Plus size={17}/> NUEVO SEGUIMIENTO</button></div><div className="follow-groups">{groups.map(([title,items])=><section className="panel" key={title}><div className="panel-head"><div><h2>{title}</h2><p>{items.length} tareas</p></div></div>{items.length?items.map(f=>{const v=db.vehicles.find(v=>v.id===f.vehicleId);return <div className={"task-row "+(title==="Atrasados"?"overdue":"")} key={f.id}><div className="date-tile"><b>{new Date(f.date+"T12:00:00").getDate()}</b><span>{new Date(f.date+"T12:00:00").toLocaleDateString("es-CR",{month:"short"}).toUpperCase()}</span></div><div className="grow"><b>{v?`${v.brand} ${v.model} ${v.year}`:"Sin vehículo"}</b><span>{f.description} · {f.person}</span></div><span>{f.time}</span>{f.status!=="Completado"&&<button className="icon-btn success" title="Completar" onClick={()=>complete(f.id)}><CheckCircle2 size={17}/></button>}</div>}):<p className="muted">Sin tareas.</p>}</section>)}</div></>
}
function FollowupModal({db,update,onClose}){
 const [f,setF]=useState({date:today(),time:"10:00",vehicleId:"",person:"",type:"Interesado",description:"",status:"Pendiente"});const set=(k,v)=>setF(x=>({...x,[k]:v}));
 const submit=e=>{e.preventDefault();update(d=>({...d,followups:[...d.followups,{...f,id:nextId(d.followups,"F")}] }));onClose()};
 return <Modal title="Nuevo seguimiento" onClose={onClose}><form onSubmit={submit}><div className="form-grid"><Field label="Fecha"><input type="date" required value={f.date} onChange={e=>set("date",e.target.value)}/></Field><Field label="Hora"><input type="time" value={f.time} onChange={e=>set("time",e.target.value)}/></Field><Field label="Vehículo"><select value={f.vehicleId} onChange={e=>set("vehicleId",e.target.value)}><option value="">Seleccionar...</option>{db.vehicles.map(v=><option key={v.id} value={v.id}>{v.id} · {v.brand} {v.model}</option>)}</select></Field><Field label="Propietario / interesado"><input value={f.person} onChange={e=>set("person",e.target.value)}/></Field><Field label="Tipo"><select value={f.type} onChange={e=>set("type",e.target.value)}><option>Propietario</option><option>Interesado</option><option>Publicación</option><option>Venta</option><option>Otro</option></select></Field></div><Field label="Descripción"><textarea required rows="4" value={f.description} onChange={e=>set("description",e.target.value)}/></Field><div className="modal-foot"><button type="button" className="btn" onClick={onClose}>Cancelar</button><button className="btn primary">Guardar seguimiento</button></div></form></Modal>
}
function Sales({db,update}){
 const [open,setOpen]=useState(null); const [f,setF]=useState({buyer:"",priceFinal:"",date:today(),commissionStatus:"Pendiente"});
 const sold=db.sales; const total=sold.reduce((a,s)=>a+s.priceFinal,0), comm=sold.reduce((a,s)=>a+s.commission,0), paid=sold.filter(s=>s.commissionStatus==="Pagada").reduce((a,s)=>a+s.commission,0);
 const markPaid=id=>update(d=>({...d,sales:d.sales.map(s=>s.id===id?{...s,commissionStatus:"Pagada"}:s)}));
 const submit=e=>{e.preventDefault();const v=db.vehicles.find(v=>v.id===open);update(d=>{const price=Number(f.priceFinal)||0;const sale={id:nextId(d.sales,"SALE"),vehicleId:v.id,owner:v.owner,buyer:f.buyer,pricePublished:v.price,priceFinal:price,commissionPct:v.commissionPct,commission:price*v.commissionPct/100,commissionStatus:f.commissionStatus,date:f.date};return {...d,sales:[...d.sales,sale],vehicles:d.vehicles.map(x=>x.id===v.id?{...x,status:"Vendido",activity:[...(x.activity||[]),{date:f.date,text:"Venta realizada."}]}:x)}});setOpen(null)};
 return <><div className="page-head"><div><div className="eyebrow">CIERRES</div><h1>Ventas</h1><p>Historial de ventas y comisiones.</p></div></div><div className="kpis compact"><Kpi icon={BadgeDollarSign} label="Ventas del año" value={sold.length} meta="Cierres registrados"/><Kpi icon={Wallet} label="Total vendido" value={money(total)} meta="Precio final"/><Kpi icon={TrendingUp} label="Comisiones generadas" value={money(comm)} meta="Todas las ventas"/><Kpi icon={CheckCircle2} label="Comisiones cobradas" value={money(paid)} meta="Pagadas"/></div><section className="panel table-panel"><div className="table-scroll"><table><thead><tr><th>Vehículo</th><th>Propietario</th><th>Comprador</th><th>Publicado</th><th>Precio final</th><th>Comisión</th><th>Estado</th><th>Fecha</th><th></th></tr></thead><tbody>{sold.map(s=>{const v=db.vehicles.find(v=>v.id===s.vehicleId);return <tr key={s.id}><td><b>{v?`${v.brand} ${v.model} ${v.year}`:s.vehicleId}</b><small>{s.vehicleId}</small></td><td>{s.owner}</td><td>{s.buyer}</td><td>{money(s.pricePublished)}</td><td><b>{money(s.priceFinal)}</b></td><td>{money(s.commission)}<small>{s.commissionPct}%</small></td><td><button className={s.commissionStatus==="Pagada"?"status paid":"status pending"} onClick={()=>markPaid(s.id)}>{s.commissionStatus}</button></td><td>{dateFmt(s.date)}</td><td></td></tr>})}</tbody></table></div>{!sold.length&&<Empty title="Aún no hay ventas" text="Cuando cierres una operación, regístrala aquí."/>}</section><div className="sale-quick"><h3>Marcar vehículo como vendido</h3><select value={open||""} onChange={e=>setOpen(e.target.value||null)}><option value="">Seleccionar vehículo...</option>{db.vehicles.filter(v=>!["Vendido","Retirado"].includes(v.status)).map(v=><option key={v.id} value={v.id}>{v.id} · {v.brand} {v.model} — {money(v.price)}</option>)}</select>{open&&<form onSubmit={submit} className="inline-form"><Field label="Comprador"><input required value={f.buyer} onChange={e=>setF({...f,buyer:e.target.value})}/></Field><Field label="Precio final"><input type="number" required value={f.priceFinal} onChange={e=>setF({...f,priceFinal:e.target.value})}/></Field><Field label="Fecha de venta"><input type="date" value={f.date} onChange={e=>setF({...f,date:e.target.value})}/></Field><button className="btn primary">Registrar venta</button></form>}</div></>
}
function Documents({db,update}){
 const [f,setF]=useState({name:"",type:"Contrato de intermediación",vehicleId:"",ownerId:""}); const [file,setFile]=useState(null);
 const add=e=>{e.preventDefault();if(!file)return;const reader=new FileReader();reader.onload=()=>{update(d=>({...d,documents:[...d.documents,{id:nextId(d.documents,"DOC"),name:f.name||file.name,type:f.type,vehicleId:f.vehicleId,ownerId:f.ownerId,date:today(),data:reader.result,size:file.size}] }));setFile(null);setF({...f,name:""});};reader.readAsDataURL(file)};
 const downloadDoc=d=>{const a=document.createElement("a");a.href=d.data;a.download=d.name;a.click()};
 return <><div className="page-head"><div><div className="eyebrow">ARCHIVO</div><h1>Documentos</h1><p>Asocia y conserva documentos de vehículos y propietarios.</p></div></div><section className="panel"><form className="upload-form" onSubmit={add}><Field label="Archivo"><input type="file" required onChange={e=>setFile(e.target.files?.[0]||null)}/></Field><Field label="Nombre"><input value={f.name} onChange={e=>setF({...f,name:e.target.value})} placeholder="Nombre opcional"/></Field><Field label="Tipo"><select value={f.type} onChange={e=>setF({...f,type:e.target.value})}><option>Contrato de intermediación</option><option>Documento de identidad</option><option>Documentación del vehículo</option><option>Fotografías</option><option>Otros</option></select></Field><Field label="Vehículo"><select value={f.vehicleId} onChange={e=>setF({...f,vehicleId:e.target.value})}><option value="">Ninguno</option>{db.vehicles.map(v=><option key={v.id} value={v.id}>{v.id} · {v.brand} {v.model}</option>)}</select></Field><button className="btn primary"><Upload size={16}/> Subir documento</button></form></section><section className="panel table-panel"><div className="table-scroll"><table><thead><tr><th>Nombre</th><th>Tipo</th><th>Fecha</th><th>Vehículo</th><th>Tamaño</th><th></th></tr></thead><tbody>{db.documents.map(d=><tr key={d.id}><td><b>{d.name}</b></td><td>{d.type}</td><td>{dateFmt(d.date)}</td><td>{d.vehicleId||"—"}</td><td>{Math.round(d.size/1024)} KB</td><td><div className="row-actions"><button className="icon-btn" onClick={()=>downloadDoc(d)}><Download size={16}/></button><button className="icon-btn danger" onClick={()=>update(x=>({...x,documents:x.documents.filter(z=>z.id!==d.id)}))}><Trash2 size={16}/></button></div></td></tr>)}</tbody></table></div>{!db.documents.length&&<Empty title="No hay documentos" text="Sube contratos, identificaciones o documentación de vehículos."/>}</section></>
}
function Reports({db}){
 const counts=Object.fromEntries(statuses.map(s=>[s,db.vehicles.filter(v=>v.status===s).length])); const max=Math.max(1,...Object.values(counts)); const brands={};db.vehicles.forEach(v=>brands[v.brand]=(brands[v.brand]||0)+1);const maxB=Math.max(1,...Object.values(brands)); const inv=db.vehicles.filter(v=>!["Vendido","Retirado"].includes(v.status)).reduce((a,v)=>a+v.price,0);const comm=db.sales.reduce((a,s)=>a+s.commission,0),paid=db.sales.filter(s=>s.commissionStatus==="Pagada").reduce((a,s)=>a+s.commission,0);
 return <><div className="page-head"><div><div className="eyebrow">ANALÍTICA</div><h1>Reportes</h1><p>Lectura rápida del desempeño de tu cartera.</p></div></div><div className="report-grid"><ReportPanel title="Vehículos por estado"><div className="bars">{statuses.map(s=><div className="bar-row" key={s}><span>{s}</span><div className="bar"><i style={{width:`${counts[s]/max*100}%`}}></i></div><b>{counts[s]}</b></div>)}</div></ReportPanel><ReportPanel title="Valor del inventario"><div className="report-number">{money(inv)}</div><p className="muted">Valor de publicación de vehículos activos.</p></ReportPanel><ReportPanel title="Comisiones"><div className="commission-bars"><div><span>Generadas</span><strong>{money(comm)}</strong></div><div><span>Pagadas</span><strong>{money(paid)}</strong></div><div><span>Pendientes</span><strong>{money(comm-paid)}</strong></div></div></ReportPanel><ReportPanel title="Ventas por mes"><div className="mini-chart">{Array.from({length:6},(_,i)=>{const d=new Date();d.setMonth(d.getMonth()-5+i);const key=d.toISOString().slice(0,7);const n=db.sales.filter(s=>s.date.startsWith(key)).length;return <div key={key}><i style={{height:`${Math.max(8,n*28)}px`}}></i><span>{d.toLocaleDateString("es-CR",{month:"short"}).slice(0,3)}</span></div>})}</div></ReportPanel><ReportPanel title="Marcas en cartera"><div className="bars">{Object.entries(brands).sort((a,b)=>b[1]-a[1]).map(([b,n])=><div className="bar-row" key={b}><span>{b}</span><div className="bar"><i style={{width:`${n/maxB*100}%`}}></i></div><b>{n}</b></div>)}</div></ReportPanel></div></>
}
function ReportPanel({title,children}){return <section className="panel report-panel"><div className="panel-head"><h2>{title}</h2></div>{children}</section>}
function SettingsPage({db,setDb}){
 const [name,setName]=useState(db.settings.businessName),[admin,setAdmin]=useState(db.settings.adminName);
 const save=()=>{const n={...db,settings:{businessName:name,adminName:admin}};setDb(n);saveDB(n);alert("Configuración guardada.")};
 return <><div className="page-head"><div><div className="eyebrow">SISTEMA</div><h1>Configuración</h1><p>Preferencias y mantenimiento de la aplicación.</p></div></div><div className="settings-grid"><section className="panel"><div className="panel-head"><h2>Empresa</h2></div><Field label="Nombre de la empresa"><input value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Administrador"><input value={admin} onChange={e=>setAdmin(e.target.value)}/></Field><button className="btn primary" onClick={save}>Guardar cambios</button></section><section className="panel"><div className="panel-head"><h2>Datos</h2></div><p className="muted">Los datos se almacenan en este navegador mediante LocalStorage y permanecen al recargar.</p><div className="settings-actions"><button className="btn" onClick={()=>{const blob=new Blob([JSON.stringify(db,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="herrera-auto-sales-backup.json";a.click()}}><Download size={16}/> Exportar respaldo</button><button className="btn danger-btn" onClick={()=>{if(confirm("¿Restaurar datos demo? Se reemplazará la información actual.")){const n=resetDemo();setDb(n)}}}><RefreshCw size={16}/> Restaurar demo</button><button className="btn danger-btn" onClick={()=>{if(confirm("¿Eliminar TODOS los datos?")){const n=emptyDB();setDb(n);saveDB(n)}}}><Trash2 size={16}/> Vaciar base local</button></div></section></div></>
}
